# Generated by Django 6.0.4 on 2026-04-18 08:24

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Short human-readable description of what happened.', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who triggered the event (null = system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the subject, e.g. 'Cloud Computing 101'.", max_length=150)),
                ('code', models.CharField(blank=True, help_text="Optional short subject code, e.g. 'CC-101'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, help_text='Students enrolled in this subject.', limit_choices_to={'role': 'STUDENT'}, related_name='subjects_enrolled', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='The teacher responsible for this subject.', limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The calendar date of the session (auto-set to today).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin_code', models.CharField(default=core.models.generate_pin, help_text='6-digit PIN students type to begin attendance.', max_length=6, unique=True)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image encoding the PIN for quick scanning.', null=True, upload_to=core.models.qr_code_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='While True, students can mark attendance for this session.')),
                ('created_by', models.ForeignKey(help_text='Teacher who started this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='The subject this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.subject')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, help_text='The exact moment the student marked attendance (face verified).', null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-session__date', 'student__last_name'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
