# Generated by Django 6.0.4 on 2026-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encodings',
            field=models.JSONField(blank=True, help_text='Averaged face embedding vector (512 floats) for recognition.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='azure_person_id',
            field=models.CharField(blank=True, help_text='Person folder ID in local face_db. Set during enrollment.', max_length=100, null=True),
        ),
    ]
